---
title: "Ariel Ma Exploratory Data Analysis Lesson 4 Quizzes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r 4.1 diamonds summary}
data(diamonds)
# You should notice that the diamonds data set will be listed as a 'Promise' in the workspace. This is a special object in R, and you   need  to run a command on the data to fully load the data set. Try running a summary:
summary(diamonds)
names(diamonds)
str(diamonds)
diamonds$color
?diamonds
```

## Including Plots

You can also embed plots, for example:

```{r 4.2 Histogram of Price, 4.5 Cheaper Diamonds}
qplot(data = diamonds, x = price, binwidth = 50, color = I('black'), fill = I('#099DD9')) + 
  scale_x_continuous(breaks = seq(0, 20000, 500)) + coord_cartesian(xlim = c(0, 3000))

summary(diamonds$price)
# mean = 3933
# median = 2401
```
```{r 4.4 Diamond Counts}

sum(diamonds$price < 500)
sum(diamonds$price < 250)
sum(diamonds$price >= 15000)
```
```{r 4.6 Price by Cut Histograms}
qplot(data = diamonds, x = price, binwidth = 500, color = I('black'), fill = I('#099DD9')) + 
  scale_x_continuous(breaks = seq(0, 20000, 500)) +
  facet_wrap(~cut)

```

```{r 4.7 Price by Cut}
by(diamonds$price, diamonds$cut, summary)
```

```{r 4.8 Scales and Multiple Histograms}
qplot(x = price, data = diamonds) + facet_wrap(~cut, scales = 'free_y')
?facet_wrap
```

```{r 4.9 Price per Carat by Cut}
qplot(x = diamonds$price/diamonds$carat, data = diamonds, binwidth = 200) + facet_wrap(~cut, scales = 'free_y')
summary(diamonds$price/diamonds$carat)
```


```{r 4.10 Price Box Plot 4.11 Interquartile Range - IQR}
qplot(data = diamonds, x = diamonds$color, y = diamonds$price, geom = 'boxplot') + coord_cartesian(ylim = c(0, 7500))

by(diamonds$price, diamonds$color, summary)
?diamonds

```

```{r 4.12 Price per Carat Box Plots by Color}
qplot(data = diamonds, x = diamonds$color, y = diamonds$price/diamonds$carat, geom = 'boxplot') + coord_cartesian(ylim = c(0, 7500))

by(diamonds$price/diamonds$carat, diamonds$color, summary)
```
```{r 4.13 Carat Frequency Polygon}
qplot(x = diamonds$carat, y = ..count..,
      data = diamonds, 
      geom = 'freqpoly', binwidth = 0.1,
      xlab = 'Diamond Weight (Carat)',
      ylab = 'Count of diamonds that have that weight') 
table(diamonds$carat)

qplot(data = diamonds, x = diamonds$carat)
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
